### ISSUE TITLE
elementOffsetTopInViewHeight is negative when element is fully visible

### ISSUE THREAD

**Issue by artemas** [miguelmota/inview#7] opened 2018-11-20 10:48 UTC
if offsetParent is not body

https://github.com/miguelmota/inview/blob/a5af808d12c0d7c0cbd35ec3119a79df48f69a71/inview.js#L134

> The offsetTop property returns the top position (in pixels) relative to the top of the offsetParent element.
https://www.w3schools.com/jsref/prop_element_offsettop.asp

**Comment by miguelmota** [comment] 2019-01-26 10:24
`elementOffsetTopInViewHeight` will be positive when the element is below the top of the viewport and negative when it is scrolled past the top of the viewport

here's a diagram to make it things a bit clearer

![inview top offset 2](https://user-images.githubusercontent.com/168240/51785958-9128aa00-2112-11e9-8eac-e302c8ca67c0.png)


closing issue since its intended behavior but let me know if you think it should be something else. You'll get negative values regardless if the offset parent is a container element or body

thanks for reporting

**Closed as completed by miguelmota** 2019-01-26 10:24 UTC
